# coding: utf-8

"""
    Orbuculum API

    Orbuculum API documentation

    The version of the OpenAPI document: 0.35.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictInt, StrictStr, field_validator
from typing import Optional
from typing_extensions import Annotated
from orbuculum_client.models.get_selection_tree200_response import GetSelectionTree200Response

from orbuculum_client.api_client import ApiClient, RequestSerialized
from orbuculum_client.api_response import ApiResponse
from orbuculum_client.rest import RESTResponseType


class SelectionApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_selection_tree(
        self,
        workspace_id: Annotated[StrictInt, Field(description="Workspace ID")],
        selection_type: Annotated[Optional[StrictStr], Field(description="Selection type filter. Allowed: all, author, counterparty, replacement, account_in_tag, commission, sending_commission, import_counterparty_list")] = None,
        mode: Annotated[Optional[StrictStr], Field(description="Tree mode. 'leaf' = entities disabled, accounts selectable. 'entities' = entities selectable, accounts disabled.")] = None,
        manageable: Annotated[Optional[StrictInt], Field(description="Filter by manage (1) or view (0) permission")] = None,
        show_hidden: Annotated[Optional[StrictInt], Field(description="Include hidden entities/accounts (0 = exclude, 1 = include)")] = None,
        account_id: Annotated[Optional[StrictInt], Field(description="Context account ID (used by counterparty, replacement, commission, sending_commission, import_counterparty_list)")] = None,
        tag_id: Annotated[Optional[StrictInt], Field(description="Context tag/group ID (used by account_in_tag)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> GetSelectionTree200Response:
        """Get filtered entity/account tree

        Returns a filtered entity→accounts tree for the universal picker component. Supports 8 selection types with different filtering logic. The 'author' type returns a user list instead of an account tree.

        :param workspace_id: Workspace ID (required)
        :type workspace_id: int
        :param selection_type: Selection type filter. Allowed: all, author, counterparty, replacement, account_in_tag, commission, sending_commission, import_counterparty_list
        :type selection_type: str
        :param mode: Tree mode. 'leaf' = entities disabled, accounts selectable. 'entities' = entities selectable, accounts disabled.
        :type mode: str
        :param manageable: Filter by manage (1) or view (0) permission
        :type manageable: int
        :param show_hidden: Include hidden entities/accounts (0 = exclude, 1 = include)
        :type show_hidden: int
        :param account_id: Context account ID (used by counterparty, replacement, commission, sending_commission, import_counterparty_list)
        :type account_id: int
        :param tag_id: Context tag/group ID (used by account_in_tag)
        :type tag_id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_selection_tree_serialize(
            workspace_id=workspace_id,
            selection_type=selection_type,
            mode=mode,
            manageable=manageable,
            show_hidden=show_hidden,
            account_id=account_id,
            tag_id=tag_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetSelectionTree200Response",
            '400': "ErrorResponse400",
            '401': "ErrorResponse401",
            '403': "ErrorResponse403",
            '500': "ErrorResponse500",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_selection_tree_with_http_info(
        self,
        workspace_id: Annotated[StrictInt, Field(description="Workspace ID")],
        selection_type: Annotated[Optional[StrictStr], Field(description="Selection type filter. Allowed: all, author, counterparty, replacement, account_in_tag, commission, sending_commission, import_counterparty_list")] = None,
        mode: Annotated[Optional[StrictStr], Field(description="Tree mode. 'leaf' = entities disabled, accounts selectable. 'entities' = entities selectable, accounts disabled.")] = None,
        manageable: Annotated[Optional[StrictInt], Field(description="Filter by manage (1) or view (0) permission")] = None,
        show_hidden: Annotated[Optional[StrictInt], Field(description="Include hidden entities/accounts (0 = exclude, 1 = include)")] = None,
        account_id: Annotated[Optional[StrictInt], Field(description="Context account ID (used by counterparty, replacement, commission, sending_commission, import_counterparty_list)")] = None,
        tag_id: Annotated[Optional[StrictInt], Field(description="Context tag/group ID (used by account_in_tag)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[GetSelectionTree200Response]:
        """Get filtered entity/account tree

        Returns a filtered entity→accounts tree for the universal picker component. Supports 8 selection types with different filtering logic. The 'author' type returns a user list instead of an account tree.

        :param workspace_id: Workspace ID (required)
        :type workspace_id: int
        :param selection_type: Selection type filter. Allowed: all, author, counterparty, replacement, account_in_tag, commission, sending_commission, import_counterparty_list
        :type selection_type: str
        :param mode: Tree mode. 'leaf' = entities disabled, accounts selectable. 'entities' = entities selectable, accounts disabled.
        :type mode: str
        :param manageable: Filter by manage (1) or view (0) permission
        :type manageable: int
        :param show_hidden: Include hidden entities/accounts (0 = exclude, 1 = include)
        :type show_hidden: int
        :param account_id: Context account ID (used by counterparty, replacement, commission, sending_commission, import_counterparty_list)
        :type account_id: int
        :param tag_id: Context tag/group ID (used by account_in_tag)
        :type tag_id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_selection_tree_serialize(
            workspace_id=workspace_id,
            selection_type=selection_type,
            mode=mode,
            manageable=manageable,
            show_hidden=show_hidden,
            account_id=account_id,
            tag_id=tag_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetSelectionTree200Response",
            '400': "ErrorResponse400",
            '401': "ErrorResponse401",
            '403': "ErrorResponse403",
            '500': "ErrorResponse500",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_selection_tree_without_preload_content(
        self,
        workspace_id: Annotated[StrictInt, Field(description="Workspace ID")],
        selection_type: Annotated[Optional[StrictStr], Field(description="Selection type filter. Allowed: all, author, counterparty, replacement, account_in_tag, commission, sending_commission, import_counterparty_list")] = None,
        mode: Annotated[Optional[StrictStr], Field(description="Tree mode. 'leaf' = entities disabled, accounts selectable. 'entities' = entities selectable, accounts disabled.")] = None,
        manageable: Annotated[Optional[StrictInt], Field(description="Filter by manage (1) or view (0) permission")] = None,
        show_hidden: Annotated[Optional[StrictInt], Field(description="Include hidden entities/accounts (0 = exclude, 1 = include)")] = None,
        account_id: Annotated[Optional[StrictInt], Field(description="Context account ID (used by counterparty, replacement, commission, sending_commission, import_counterparty_list)")] = None,
        tag_id: Annotated[Optional[StrictInt], Field(description="Context tag/group ID (used by account_in_tag)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get filtered entity/account tree

        Returns a filtered entity→accounts tree for the universal picker component. Supports 8 selection types with different filtering logic. The 'author' type returns a user list instead of an account tree.

        :param workspace_id: Workspace ID (required)
        :type workspace_id: int
        :param selection_type: Selection type filter. Allowed: all, author, counterparty, replacement, account_in_tag, commission, sending_commission, import_counterparty_list
        :type selection_type: str
        :param mode: Tree mode. 'leaf' = entities disabled, accounts selectable. 'entities' = entities selectable, accounts disabled.
        :type mode: str
        :param manageable: Filter by manage (1) or view (0) permission
        :type manageable: int
        :param show_hidden: Include hidden entities/accounts (0 = exclude, 1 = include)
        :type show_hidden: int
        :param account_id: Context account ID (used by counterparty, replacement, commission, sending_commission, import_counterparty_list)
        :type account_id: int
        :param tag_id: Context tag/group ID (used by account_in_tag)
        :type tag_id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_selection_tree_serialize(
            workspace_id=workspace_id,
            selection_type=selection_type,
            mode=mode,
            manageable=manageable,
            show_hidden=show_hidden,
            account_id=account_id,
            tag_id=tag_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetSelectionTree200Response",
            '400': "ErrorResponse400",
            '401': "ErrorResponse401",
            '403': "ErrorResponse403",
            '500': "ErrorResponse500",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_selection_tree_serialize(
        self,
        workspace_id,
        selection_type,
        mode,
        manageable,
        show_hidden,
        account_id,
        tag_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if workspace_id is not None:
            
            _query_params.append(('workspace_id', workspace_id))
            
        if selection_type is not None:
            
            _query_params.append(('selection_type', selection_type))
            
        if mode is not None:
            
            _query_params.append(('mode', mode))
            
        if manageable is not None:
            
            _query_params.append(('manageable', manageable))
            
        if show_hidden is not None:
            
            _query_params.append(('show_hidden', show_hidden))
            
        if account_id is not None:
            
            _query_params.append(('account_id', account_id))
            
        if tag_id is not None:
            
            _query_params.append(('tag_id', tag_id))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'bearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/selection/tree',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


