# coding: utf-8

"""
    Orbuculum API

    Orbuculum API documentation

    The version of the OpenAPI document: 0.11.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from orbuculum_client.models.bulk_assign_permissions_request_permissions_account_groups_inner import BulkAssignPermissionsRequestPermissionsAccountGroupsInner
from orbuculum_client.models.bulk_assign_permissions_request_permissions_entities_inner import BulkAssignPermissionsRequestPermissionsEntitiesInner
from orbuculum_client.models.bulk_assign_permissions_request_permissions_labels_inner import BulkAssignPermissionsRequestPermissionsLabelsInner
from typing import Optional, Set
from typing_extensions import Self

class BulkAssignPermissionsRequestPermissions(BaseModel):
    """
    Permissions to assign, grouped by type
    """ # noqa: E501
    general: Optional[List[StrictStr]] = Field(default=None, description="General permission names (max 10)")
    entities: Optional[List[BulkAssignPermissionsRequestPermissionsEntitiesInner]] = Field(default=None, description="Entity permissions (max 20)")
    account_groups: Optional[List[BulkAssignPermissionsRequestPermissionsAccountGroupsInner]] = Field(default=None, description="Account group permissions (max 20)")
    labels: Optional[List[BulkAssignPermissionsRequestPermissionsLabelsInner]] = Field(default=None, description="Label permissions (max 20)")
    __properties: ClassVar[List[str]] = ["general", "entities", "account_groups", "labels"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BulkAssignPermissionsRequestPermissions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in entities (list)
        _items = []
        if self.entities:
            for _item_entities in self.entities:
                if _item_entities:
                    _items.append(_item_entities.to_dict())
            _dict['entities'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in account_groups (list)
        _items = []
        if self.account_groups:
            for _item_account_groups in self.account_groups:
                if _item_account_groups:
                    _items.append(_item_account_groups.to_dict())
            _dict['account_groups'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in labels (list)
        _items = []
        if self.labels:
            for _item_labels in self.labels:
                if _item_labels:
                    _items.append(_item_labels.to_dict())
            _dict['labels'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BulkAssignPermissionsRequestPermissions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "general": obj.get("general"),
            "entities": [BulkAssignPermissionsRequestPermissionsEntitiesInner.from_dict(_item) for _item in obj["entities"]] if obj.get("entities") is not None else None,
            "account_groups": [BulkAssignPermissionsRequestPermissionsAccountGroupsInner.from_dict(_item) for _item in obj["account_groups"]] if obj.get("account_groups") is not None else None,
            "labels": [BulkAssignPermissionsRequestPermissionsLabelsInner.from_dict(_item) for _item in obj["labels"]] if obj.get("labels") is not None else None
        })
        return _obj


