# coding: utf-8

"""
    Orbuculum API

    Orbuculum API documentation

    The version of the OpenAPI document: 0.134.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List
from orbuculum_client.models.cashflow_report_response_data_periods_inner_balances_inner import CashflowReportResponseDataPeriodsInnerBalancesInner
from orbuculum_client.models.cashflow_report_response_data_periods_inner_financing_inner import CashflowReportResponseDataPeriodsInnerFinancingInner
from orbuculum_client.models.cashflow_report_response_data_periods_inner_inflow_inner import CashflowReportResponseDataPeriodsInnerInflowInner
from orbuculum_client.models.cashflow_report_response_data_periods_inner_outflow_inner import CashflowReportResponseDataPeriodsInnerOutflowInner
from orbuculum_client.models.cashflow_report_response_data_periods_inner_period import CashflowReportResponseDataPeriodsInnerPeriod
from orbuculum_client.models.cashflow_report_response_data_periods_inner_totals import CashflowReportResponseDataPeriodsInnerTotals
from typing import Optional, Set
from typing_extensions import Self

class CashflowReportResponseDataPeriodsInner(BaseModel):
    """
    CashflowReportResponseDataPeriodsInner
    """ # noqa: E501
    period: CashflowReportResponseDataPeriodsInnerPeriod
    inflow: List[CashflowReportResponseDataPeriodsInnerInflowInner] = Field(description="Operating cash inflow rows. Signs are emitted exactly as the backend computes them.")
    outflow: List[CashflowReportResponseDataPeriodsInnerOutflowInner] = Field(description="Operating cash outflow rows. Amounts arrive negative; nothing is inverted.")
    financing: List[CashflowReportResponseDataPeriodsInnerFinancingInner] = Field(description="Financing rows. Empty off the workspace's default label, where the report computes no financing section.")
    revaluation: StrictInt = Field(description="Cash revaluation for the period — the value the legacy response shipped under forex_gains. On the default label it is already folded into totals.financing and is not added again.")
    balances: List[CashflowReportResponseDataPeriodsInnerBalancesInner] = Field(description="End-of-period balances, concatenated accounts then debts then other. account.type is one of debt, account, cf_account.")
    totals: CashflowReportResponseDataPeriodsInnerTotals
    __properties: ClassVar[List[str]] = ["period", "inflow", "outflow", "financing", "revaluation", "balances", "totals"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CashflowReportResponseDataPeriodsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of period
        if self.period:
            _dict['period'] = self.period.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in inflow (list)
        _items = []
        if self.inflow:
            for _item_inflow in self.inflow:
                if _item_inflow:
                    _items.append(_item_inflow.to_dict())
            _dict['inflow'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in outflow (list)
        _items = []
        if self.outflow:
            for _item_outflow in self.outflow:
                if _item_outflow:
                    _items.append(_item_outflow.to_dict())
            _dict['outflow'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in financing (list)
        _items = []
        if self.financing:
            for _item_financing in self.financing:
                if _item_financing:
                    _items.append(_item_financing.to_dict())
            _dict['financing'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in balances (list)
        _items = []
        if self.balances:
            for _item_balances in self.balances:
                if _item_balances:
                    _items.append(_item_balances.to_dict())
            _dict['balances'] = _items
        # override the default output from pydantic by calling `to_dict()` of totals
        if self.totals:
            _dict['totals'] = self.totals.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CashflowReportResponseDataPeriodsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "period": CashflowReportResponseDataPeriodsInnerPeriod.from_dict(obj["period"]) if obj.get("period") is not None else None,
            "inflow": [CashflowReportResponseDataPeriodsInnerInflowInner.from_dict(_item) for _item in obj["inflow"]] if obj.get("inflow") is not None else None,
            "outflow": [CashflowReportResponseDataPeriodsInnerOutflowInner.from_dict(_item) for _item in obj["outflow"]] if obj.get("outflow") is not None else None,
            "financing": [CashflowReportResponseDataPeriodsInnerFinancingInner.from_dict(_item) for _item in obj["financing"]] if obj.get("financing") is not None else None,
            "revaluation": obj.get("revaluation"),
            "balances": [CashflowReportResponseDataPeriodsInnerBalancesInner.from_dict(_item) for _item in obj["balances"]] if obj.get("balances") is not None else None,
            "totals": CashflowReportResponseDataPeriodsInnerTotals.from_dict(obj["totals"]) if obj.get("totals") is not None else None
        })
        return _obj


