# coding: utf-8

"""
    Orbuculum API

    Orbuculum API documentation

    The version of the OpenAPI document: 0.39.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, Dict, List, Optional
from typing_extensions import Annotated
from orbuculum_client.models.cashflow_report_response_data_operating_activities_cash_inflow_value import CashflowReportResponseDataOperatingActivitiesCashInflowValue
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

CASHFLOWREPORTRESPONSEDATAFINANCIALACTIVITIES_ONE_OF_SCHEMAS = ["Dict[str, CashflowReportResponseDataOperatingActivitiesCashInflowValue]", "List[str]"]

class CashflowReportResponseDataFinancialActivities(BaseModel):
    """
    Financial activities rows keyed by account ID; special key 'total'. Empty when label_id != default label.
    """
    # data type: Dict[str, CashflowReportResponseDataOperatingActivitiesCashInflowValue]
    oneof_schema_1_validator: Optional[Dict[str, CashflowReportResponseDataOperatingActivitiesCashInflowValue]] = Field(default=None, description="Populated state — rows keyed by account ID")
    # data type: List[str]
    oneof_schema_2_validator: Optional[Annotated[List[StrictStr], Field(max_length=0)]] = Field(default=None, description="Empty state — returned as empty JSON array []")
    actual_instance: Optional[Union[Dict[str, CashflowReportResponseDataOperatingActivitiesCashInflowValue], List[str]]] = None
    one_of_schemas: Set[str] = { "Dict[str, CashflowReportResponseDataOperatingActivitiesCashInflowValue]", "List[str]" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = CashflowReportResponseDataFinancialActivities.model_construct()
        error_messages = []
        match = 0
        # validate data type: Dict[str, CashflowReportResponseDataOperatingActivitiesCashInflowValue]
        try:
            instance.oneof_schema_1_validator = v
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: List[str]
        try:
            instance.oneof_schema_2_validator = v
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in CashflowReportResponseDataFinancialActivities with oneOf schemas: Dict[str, CashflowReportResponseDataOperatingActivitiesCashInflowValue], List[str]. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in CashflowReportResponseDataFinancialActivities with oneOf schemas: Dict[str, CashflowReportResponseDataOperatingActivitiesCashInflowValue], List[str]. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into Dict[str, CashflowReportResponseDataOperatingActivitiesCashInflowValue]
        try:
            # validation
            instance.oneof_schema_1_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.oneof_schema_1_validator
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into List[str]
        try:
            # validation
            instance.oneof_schema_2_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.oneof_schema_2_validator
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into CashflowReportResponseDataFinancialActivities with oneOf schemas: Dict[str, CashflowReportResponseDataOperatingActivitiesCashInflowValue], List[str]. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into CashflowReportResponseDataFinancialActivities with oneOf schemas: Dict[str, CashflowReportResponseDataOperatingActivitiesCashInflowValue], List[str]. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], Dict[str, CashflowReportResponseDataOperatingActivitiesCashInflowValue], List[str]]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


