# coding: utf-8

"""
    Orbuculum API

    Orbuculum API documentation

    The version of the OpenAPI document: 0.145.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from orbuculum_client.models.cashflow_report_response_data_periods_inner import CashflowReportResponseDataPeriodsInner
from orbuculum_client.models.project import Project
from orbuculum_client.models.report_basic_currency import ReportBasicCurrency
from orbuculum_client.models.report_effective_filters import ReportEffectiveFilters
from typing import Optional, Set
from typing_extensions import Self

class CashflowReportResponseData(BaseModel):
    """
    Cash Flow report payload
    """ # noqa: E501
    periods: List[CashflowReportResponseDataPeriodsInner] = Field(description="One entry per reported period, ascending. The warm-up column that precedes date_range_from is not on the wire.")
    basic_currency: ReportBasicCurrency
    timezone: StrictStr
    available_labels: List[Project] = Field(description="Labels the caller may pick from, as a real list.")
    first_label: Optional[Project] = None
    selected_label_id: StrictInt = Field(description="The label the report actually ran on.")
    effective_filters: ReportEffectiveFilters
    date_min: Optional[date] = Field(default=None, description="First day of the window the report ran on, in the request timezone: the applied date_from (full_period off, including the current_only window), else the earliest periods[].period.from. Always present on a 200; null only when no date was applied and periods[] is empty. The SPA's calendar fallback (BE-108).")
    date_max: Optional[date] = Field(default=None, description="Last day of the window the report ran on, inclusive, in the request timezone: the applied date_to (full_period off, including the current_only window), else the latest periods[].period.to - with full_period off the day before it, since that column closes on an exclusive boundary. Always present on a 200; null only when no date was applied and periods[] is empty.")
    __properties: ClassVar[List[str]] = ["periods", "basic_currency", "timezone", "available_labels", "first_label", "selected_label_id", "effective_filters", "date_min", "date_max"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CashflowReportResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in periods (list)
        _items = []
        if self.periods:
            for _item_periods in self.periods:
                if _item_periods:
                    _items.append(_item_periods.to_dict())
            _dict['periods'] = _items
        # override the default output from pydantic by calling `to_dict()` of basic_currency
        if self.basic_currency:
            _dict['basic_currency'] = self.basic_currency.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in available_labels (list)
        _items = []
        if self.available_labels:
            for _item_available_labels in self.available_labels:
                if _item_available_labels:
                    _items.append(_item_available_labels.to_dict())
            _dict['available_labels'] = _items
        # override the default output from pydantic by calling `to_dict()` of first_label
        if self.first_label:
            _dict['first_label'] = self.first_label.to_dict()
        # override the default output from pydantic by calling `to_dict()` of effective_filters
        if self.effective_filters:
            _dict['effective_filters'] = self.effective_filters.to_dict()
        # set to None if first_label (nullable) is None
        # and model_fields_set contains the field
        if self.first_label is None and "first_label" in self.model_fields_set:
            _dict['first_label'] = None

        # set to None if date_min (nullable) is None
        # and model_fields_set contains the field
        if self.date_min is None and "date_min" in self.model_fields_set:
            _dict['date_min'] = None

        # set to None if date_max (nullable) is None
        # and model_fields_set contains the field
        if self.date_max is None and "date_max" in self.model_fields_set:
            _dict['date_max'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CashflowReportResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "periods": [CashflowReportResponseDataPeriodsInner.from_dict(_item) for _item in obj["periods"]] if obj.get("periods") is not None else None,
            "basic_currency": ReportBasicCurrency.from_dict(obj["basic_currency"]) if obj.get("basic_currency") is not None else None,
            "timezone": obj.get("timezone"),
            "available_labels": [Project.from_dict(_item) for _item in obj["available_labels"]] if obj.get("available_labels") is not None else None,
            "first_label": Project.from_dict(obj["first_label"]) if obj.get("first_label") is not None else None,
            "selected_label_id": obj.get("selected_label_id"),
            "effective_filters": ReportEffectiveFilters.from_dict(obj["effective_filters"]) if obj.get("effective_filters") is not None else None,
            "date_min": obj.get("date_min"),
            "date_max": obj.get("date_max")
        })
        return _obj


