# coding: utf-8

"""
    Orbuculum API

    Orbuculum API documentation

    The version of the OpenAPI document: 0.59.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from orbuculum_client.models.cashflow_report_response_data_end_period_balances_total import CashflowReportResponseDataEndPeriodBalancesTotal
from orbuculum_client.models.cashflow_report_response_data_operating_activities_cash_inflow_value import CashflowReportResponseDataOperatingActivitiesCashInflowValue
from typing import Optional, Set
from typing_extensions import Self

class CashflowReportResponseDataEndPeriodBalances(BaseModel):
    """
    End-of-period balance sections
    """ # noqa: E501
    accounts: Optional[Dict[str, CashflowReportResponseDataOperatingActivitiesCashInflowValue]] = Field(default=None, description="Account balance rows keyed by account ID")
    debts: Optional[Dict[str, CashflowReportResponseDataOperatingActivitiesCashInflowValue]] = Field(default=None, description="Debt balance rows keyed by account ID")
    other: Optional[Dict[str, CashflowReportResponseDataOperatingActivitiesCashInflowValue]] = Field(default=None, description="Other balance rows keyed by account ID")
    total: Optional[CashflowReportResponseDataEndPeriodBalancesTotal] = None
    __properties: ClassVar[List[str]] = ["accounts", "debts", "other", "total"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CashflowReportResponseDataEndPeriodBalances from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in accounts (dict)
        _field_dict = {}
        if self.accounts:
            for _key_accounts in self.accounts:
                if self.accounts[_key_accounts]:
                    _field_dict[_key_accounts] = self.accounts[_key_accounts].to_dict()
            _dict['accounts'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in debts (dict)
        _field_dict = {}
        if self.debts:
            for _key_debts in self.debts:
                if self.debts[_key_debts]:
                    _field_dict[_key_debts] = self.debts[_key_debts].to_dict()
            _dict['debts'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in other (dict)
        _field_dict = {}
        if self.other:
            for _key_other in self.other:
                if self.other[_key_other]:
                    _field_dict[_key_other] = self.other[_key_other].to_dict()
            _dict['other'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of total
        if self.total:
            _dict['total'] = self.total.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CashflowReportResponseDataEndPeriodBalances from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "accounts": dict(
                (_k, CashflowReportResponseDataOperatingActivitiesCashInflowValue.from_dict(_v))
                for _k, _v in obj["accounts"].items()
            )
            if obj.get("accounts") is not None
            else None,
            "debts": dict(
                (_k, CashflowReportResponseDataOperatingActivitiesCashInflowValue.from_dict(_v))
                for _k, _v in obj["debts"].items()
            )
            if obj.get("debts") is not None
            else None,
            "other": dict(
                (_k, CashflowReportResponseDataOperatingActivitiesCashInflowValue.from_dict(_v))
                for _k, _v in obj["other"].items()
            )
            if obj.get("other") is not None
            else None,
            "total": CashflowReportResponseDataEndPeriodBalancesTotal.from_dict(obj["total"]) if obj.get("total") is not None else None
        })
        return _obj


