# coding: utf-8

"""
    Orbuculum API

    Orbuculum API documentation

    The version of the OpenAPI document: 0.140.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List
from orbuculum_client.models.cashflow_report_response_data_periods_inner_financing_rows_inner import CashflowReportResponseDataPeriodsInnerFinancingRowsInner
from typing import Optional, Set
from typing_extensions import Self

class CashflowReportResponseDataPeriodsInnerFinancing(BaseModel):
    """
    Financial activities for the period, as one group: the financing rows, the cash revaluation, the financing total and free cash after financing. Always sent. The group in every period when the report ran on the workspace's default label, even when every amount is 0; null in every period on any other label and on All data (project_id=0), revaluation included.
    """ # noqa: E501
    rows: List[CashflowReportResponseDataPeriodsInnerFinancingRowsInner] = Field(description="Financing account rows.")
    revaluation: StrictInt = Field(description="Cash revaluation for the period — the value the legacy response shipped under forex_gains. It is already folded into total and is not added again.")
    total: StrictInt = Field(description="Financing total for the period, revaluation included.")
    free_cash_after_financing: StrictInt = Field(description="Free cash after financing: totals.free_cash plus total.")
    __properties: ClassVar[List[str]] = ["rows", "revaluation", "total", "free_cash_after_financing"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CashflowReportResponseDataPeriodsInnerFinancing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in rows (list)
        _items = []
        if self.rows:
            for _item_rows in self.rows:
                if _item_rows:
                    _items.append(_item_rows.to_dict())
            _dict['rows'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CashflowReportResponseDataPeriodsInnerFinancing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "rows": [CashflowReportResponseDataPeriodsInnerFinancingRowsInner.from_dict(_item) for _item in obj["rows"]] if obj.get("rows") is not None else None,
            "revaluation": obj.get("revaluation"),
            "total": obj.get("total"),
            "free_cash_after_financing": obj.get("free_cash_after_financing")
        })
        return _obj


