# coding: utf-8

"""
    Orbuculum API

    Orbuculum API documentation

    The version of the OpenAPI document: 0.35.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class CommissionData(BaseModel):
    """
    Commission calculation data
    """ # noqa: E501
    sender_amount: StrictStr = Field(description="Commission sender amount")
    receiver_amount: StrictStr = Field(description="Commission receiver amount")
    sender_account_id: Optional[StrictInt] = Field(default=None, description="Override commission sender account ID")
    receiver_account_id: Optional[StrictInt] = Field(default=None, description="Override commission receiver account ID")
    __properties: ClassVar[List[str]] = ["sender_amount", "receiver_amount", "sender_account_id", "receiver_account_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CommissionData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if sender_account_id (nullable) is None
        # and model_fields_set contains the field
        if self.sender_account_id is None and "sender_account_id" in self.model_fields_set:
            _dict['sender_account_id'] = None

        # set to None if receiver_account_id (nullable) is None
        # and model_fields_set contains the field
        if self.receiver_account_id is None and "receiver_account_id" in self.model_fields_set:
            _dict['receiver_account_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CommissionData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sender_amount": obj.get("sender_amount"),
            "receiver_amount": obj.get("receiver_amount"),
            "sender_account_id": obj.get("sender_account_id"),
            "receiver_account_id": obj.get("receiver_account_id")
        })
        return _obj


