# coding: utf-8

"""
    Orbuculum API

    Orbuculum API documentation

    The version of the OpenAPI document: 0.39.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class CreateImportRequest(BaseModel):
    """
    CreateImportRequest
    """ # noqa: E501
    workspace_id: StrictInt = Field(description="Workspace ID")
    account_id: StrictInt = Field(description="Target account ID")
    import_key: StrictStr = Field(description="Import key from preview step")
    timezone: Optional[StrictStr] = Field(default=None, description="User timezone")
    source_type: Optional[StrictStr] = Field(default=None, description="Import source type")
    target_account_id: Optional[StrictInt] = Field(default=None, description="Target account ID for AccountAssociation")
    target_hash: Optional[StrictStr] = Field(default=None, description="Target hash for AccountAssociation (blockchain address)")
    data: Optional[Dict[str, Any]] = Field(default=None, description="Last-minute edits keyed by transaction ID")
    __properties: ClassVar[List[str]] = ["workspace_id", "account_id", "import_key", "timezone", "source_type", "target_account_id", "target_hash", "data"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateImportRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if source_type (nullable) is None
        # and model_fields_set contains the field
        if self.source_type is None and "source_type" in self.model_fields_set:
            _dict['source_type'] = None

        # set to None if target_account_id (nullable) is None
        # and model_fields_set contains the field
        if self.target_account_id is None and "target_account_id" in self.model_fields_set:
            _dict['target_account_id'] = None

        # set to None if target_hash (nullable) is None
        # and model_fields_set contains the field
        if self.target_hash is None and "target_hash" in self.model_fields_set:
            _dict['target_hash'] = None

        # set to None if data (nullable) is None
        # and model_fields_set contains the field
        if self.data is None and "data" in self.model_fields_set:
            _dict['data'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateImportRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "workspace_id": obj.get("workspace_id"),
            "account_id": obj.get("account_id"),
            "import_key": obj.get("import_key"),
            "timezone": obj.get("timezone"),
            "source_type": obj.get("source_type"),
            "target_account_id": obj.get("target_account_id"),
            "target_hash": obj.get("target_hash"),
            "data": obj.get("data")
        })
        return _obj


