# coding: utf-8

"""
    Orbuculum API

    Orbuculum API documentation

    The version of the OpenAPI document: 0.39.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GetWorkspaceContext200ResponseData(BaseModel):
    """
    GetWorkspaceContext200ResponseData
    """ # noqa: E501
    account_types: Optional[Dict[str, Any]] = Field(default=None, description="Account types keyed by account ID")
    currencies_and_rates: Optional[Dict[str, Any]] = Field(default=None, description="Currencies with rates keyed by currency ID")
    account_limitation_filtering: Optional[Dict[str, Any]] = Field(default=None, description="Account limitations by direction")
    account_permission_filtering: Optional[Dict[str, Any]] = Field(default=None, description="Permitted account IDs by direction")
    is_double_array: Optional[Dict[str, Any]] = Field(default=None, description="Double-entry flags by entity ID")
    receiver_order: Optional[Dict[str, Any]] = Field(default=None, description="Receiver account ordering")
    sender_order: Optional[Dict[str, Any]] = Field(default=None, description="Sender account ordering")
    available_accounts_count: Optional[StrictInt] = Field(default=None, description="Total available accounts count")
    account_to_project: Optional[Dict[str, Any]] = Field(default=None, description="Account-to-label permission mapping")
    labels: Optional[List[Dict[str, Any]]] = Field(default=None, description="Available labels")
    selected_label_id: Optional[StrictInt] = Field(default=None, description="Default selected label ID")
    preselected_receiver: Optional[StrictInt] = Field(default=None, description="Preselected receiver account ID")
    transaction: Optional[Dict[str, Any]] = Field(default=None, description="Transaction data (edit mode only)")
    commission: Optional[Dict[str, Any]] = Field(default=None, description="Commission data (edit mode only)")
    receiver_commission: Optional[Dict[str, Any]] = Field(default=None, description="Receiver commission data (edit mode only)")
    future_data: Optional[Dict[str, Any]] = Field(default=None, description="Future schedule data (edit mode only)")
    __properties: ClassVar[List[str]] = ["account_types", "currencies_and_rates", "account_limitation_filtering", "account_permission_filtering", "is_double_array", "receiver_order", "sender_order", "available_accounts_count", "account_to_project", "labels", "selected_label_id", "preselected_receiver", "transaction", "commission", "receiver_commission", "future_data"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetWorkspaceContext200ResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if selected_label_id (nullable) is None
        # and model_fields_set contains the field
        if self.selected_label_id is None and "selected_label_id" in self.model_fields_set:
            _dict['selected_label_id'] = None

        # set to None if preselected_receiver (nullable) is None
        # and model_fields_set contains the field
        if self.preselected_receiver is None and "preselected_receiver" in self.model_fields_set:
            _dict['preselected_receiver'] = None

        # set to None if transaction (nullable) is None
        # and model_fields_set contains the field
        if self.transaction is None and "transaction" in self.model_fields_set:
            _dict['transaction'] = None

        # set to None if commission (nullable) is None
        # and model_fields_set contains the field
        if self.commission is None and "commission" in self.model_fields_set:
            _dict['commission'] = None

        # set to None if receiver_commission (nullable) is None
        # and model_fields_set contains the field
        if self.receiver_commission is None and "receiver_commission" in self.model_fields_set:
            _dict['receiver_commission'] = None

        # set to None if future_data (nullable) is None
        # and model_fields_set contains the field
        if self.future_data is None and "future_data" in self.model_fields_set:
            _dict['future_data'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetWorkspaceContext200ResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "account_types": obj.get("account_types"),
            "currencies_and_rates": obj.get("currencies_and_rates"),
            "account_limitation_filtering": obj.get("account_limitation_filtering"),
            "account_permission_filtering": obj.get("account_permission_filtering"),
            "is_double_array": obj.get("is_double_array"),
            "receiver_order": obj.get("receiver_order"),
            "sender_order": obj.get("sender_order"),
            "available_accounts_count": obj.get("available_accounts_count"),
            "account_to_project": obj.get("account_to_project"),
            "labels": obj.get("labels"),
            "selected_label_id": obj.get("selected_label_id"),
            "preselected_receiver": obj.get("preselected_receiver"),
            "transaction": obj.get("transaction"),
            "commission": obj.get("commission"),
            "receiver_commission": obj.get("receiver_commission"),
            "future_data": obj.get("future_data")
        })
        return _obj


