# coding: utf-8

"""
    Orbuculum API

    Orbuculum API documentation

    The version of the OpenAPI document: 0.59.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from orbuculum_client.models.account_summary import AccountSummary
from orbuculum_client.models.enriched_transaction_item import EnrichedTransactionItem
from orbuculum_client.models.intermediary_transaction_created_data_labels_inner import IntermediaryTransactionCreatedDataLabelsInner
from orbuculum_client.models.intermediary_transaction_created_data_schedule import IntermediaryTransactionCreatedDataSchedule
from orbuculum_client.models.transaction import Transaction
from typing import Optional, Set
from typing_extensions import Self

class IntermediaryTransactionUpdatedData(BaseModel):
    """
    IntermediaryTransactionUpdatedData
    """ # noqa: E501
    preview: Optional[StrictBool] = Field(default=False, description="True when the response represents a dry-run preview (no DB writes performed). When true, all `*_id` fields are null. Present when the request had `dry_run=true`.")
    leg1_id: Optional[StrictInt] = Field(description="Updated transaction ID for leg 1 (sender → intermediary). Null in dry-run preview mode.")
    leg2_id: Optional[StrictInt] = Field(description="Updated transaction ID for leg 2 (intermediary → receiver). Null in dry-run preview mode.")
    apikey: Optional[StrictStr] = Field(default=None, description="Apikey assigned to leg1 (leg2 apikey is always null).")
    leg1_sender_commission_id: Optional[StrictInt] = Field(default=None, description="Sender commission transaction ID for leg 1. Null in dry-run preview mode or when no commission applies.")
    leg1_receiver_commission_id: Optional[StrictInt] = Field(default=None, description="Receiver commission transaction ID for leg 1. Null in dry-run preview mode or when no commission applies.")
    leg2_sender_commission_id: Optional[StrictInt] = Field(default=None, description="Sender commission transaction ID for leg 2. Null in dry-run preview mode or when no commission applies.")
    leg2_receiver_commission_id: Optional[StrictInt] = Field(default=None, description="Receiver commission transaction ID for leg 2. Null in dry-run preview mode or when no commission applies.")
    workspace_id: Optional[StrictInt] = Field(default=None, description="Workspace ID (identical for both legs).")
    dt: Optional[datetime] = Field(default=None, description="Transaction date and time (Y-m-d H:i:s, identical for both legs).")
    comment: Optional[StrictStr] = Field(default=None, description="Comment (identical for both legs; uses leg1's value).")
    description: Optional[StrictStr] = Field(default=None, description="Description (identical for both legs).")
    project_id: Optional[StrictInt] = Field(default=None, description="Label ID (legacy alias: API `project_id` = DB `label_id`). Identical for both legs.")
    done: Optional[StrictBool] = Field(default=None, description="Whether the transaction is marked done (identical for both legs).")
    forex: Optional[StrictStr] = Field(default=None, description="Forex amount (identical for both legs at create time).")
    future_id: Optional[StrictInt] = Field(default=None, description="Recurring schedule (Future) ID (identical for both legs).")
    future_edited: Optional[StrictBool] = Field(default=None, description="True when a schedule-generated transaction was manually edited.")
    import_id: Optional[StrictInt] = Field(default=None, description="Import batch ID.")
    import_hash: Optional[StrictStr] = Field(default=None, description="Content hash used by import dedup.")
    commission_applied: Optional[StrictBool] = Field(default=None, description="Whether commission_appliance deduction was applied (identical for both legs).")
    schedule: Optional[IntermediaryTransactionCreatedDataSchedule] = None
    labels: Optional[List[IntermediaryTransactionCreatedDataLabelsInner]] = Field(default=None, description="Labels attached to the transaction (same shape as Transaction.labels).")
    leg1: Transaction
    leg2: Transaction
    transactions: Optional[List[EnrichedTransactionItem]] = Field(default=None, description="Perspective-aware enriched transaction rows. Present only when the request included `account_id`.")
    removed_ids: Optional[List[StrictInt]] = Field(default=None, description="IDs of transactions removed during the update (e.g. commission rows that no longer apply). Empty array when nothing was removed.")
    summary: Optional[AccountSummary] = None
    __properties: ClassVar[List[str]] = ["preview", "leg1_id", "leg2_id", "apikey", "leg1_sender_commission_id", "leg1_receiver_commission_id", "leg2_sender_commission_id", "leg2_receiver_commission_id", "workspace_id", "dt", "comment", "description", "project_id", "done", "forex", "future_id", "future_edited", "import_id", "import_hash", "commission_applied", "schedule", "labels", "leg1", "leg2", "transactions", "removed_ids", "summary"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IntermediaryTransactionUpdatedData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of schedule
        if self.schedule:
            _dict['schedule'] = self.schedule.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in labels (list)
        _items = []
        if self.labels:
            for _item_labels in self.labels:
                if _item_labels:
                    _items.append(_item_labels.to_dict())
            _dict['labels'] = _items
        # override the default output from pydantic by calling `to_dict()` of leg1
        if self.leg1:
            _dict['leg1'] = self.leg1.to_dict()
        # override the default output from pydantic by calling `to_dict()` of leg2
        if self.leg2:
            _dict['leg2'] = self.leg2.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in transactions (list)
        _items = []
        if self.transactions:
            for _item_transactions in self.transactions:
                if _item_transactions:
                    _items.append(_item_transactions.to_dict())
            _dict['transactions'] = _items
        # override the default output from pydantic by calling `to_dict()` of summary
        if self.summary:
            _dict['summary'] = self.summary.to_dict()
        # set to None if preview (nullable) is None
        # and model_fields_set contains the field
        if self.preview is None and "preview" in self.model_fields_set:
            _dict['preview'] = None

        # set to None if leg1_id (nullable) is None
        # and model_fields_set contains the field
        if self.leg1_id is None and "leg1_id" in self.model_fields_set:
            _dict['leg1_id'] = None

        # set to None if leg2_id (nullable) is None
        # and model_fields_set contains the field
        if self.leg2_id is None and "leg2_id" in self.model_fields_set:
            _dict['leg2_id'] = None

        # set to None if apikey (nullable) is None
        # and model_fields_set contains the field
        if self.apikey is None and "apikey" in self.model_fields_set:
            _dict['apikey'] = None

        # set to None if leg1_sender_commission_id (nullable) is None
        # and model_fields_set contains the field
        if self.leg1_sender_commission_id is None and "leg1_sender_commission_id" in self.model_fields_set:
            _dict['leg1_sender_commission_id'] = None

        # set to None if leg1_receiver_commission_id (nullable) is None
        # and model_fields_set contains the field
        if self.leg1_receiver_commission_id is None and "leg1_receiver_commission_id" in self.model_fields_set:
            _dict['leg1_receiver_commission_id'] = None

        # set to None if leg2_sender_commission_id (nullable) is None
        # and model_fields_set contains the field
        if self.leg2_sender_commission_id is None and "leg2_sender_commission_id" in self.model_fields_set:
            _dict['leg2_sender_commission_id'] = None

        # set to None if leg2_receiver_commission_id (nullable) is None
        # and model_fields_set contains the field
        if self.leg2_receiver_commission_id is None and "leg2_receiver_commission_id" in self.model_fields_set:
            _dict['leg2_receiver_commission_id'] = None

        # set to None if comment (nullable) is None
        # and model_fields_set contains the field
        if self.comment is None and "comment" in self.model_fields_set:
            _dict['comment'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if project_id (nullable) is None
        # and model_fields_set contains the field
        if self.project_id is None and "project_id" in self.model_fields_set:
            _dict['project_id'] = None

        # set to None if forex (nullable) is None
        # and model_fields_set contains the field
        if self.forex is None and "forex" in self.model_fields_set:
            _dict['forex'] = None

        # set to None if future_id (nullable) is None
        # and model_fields_set contains the field
        if self.future_id is None and "future_id" in self.model_fields_set:
            _dict['future_id'] = None

        # set to None if import_id (nullable) is None
        # and model_fields_set contains the field
        if self.import_id is None and "import_id" in self.model_fields_set:
            _dict['import_id'] = None

        # set to None if import_hash (nullable) is None
        # and model_fields_set contains the field
        if self.import_hash is None and "import_hash" in self.model_fields_set:
            _dict['import_hash'] = None

        # set to None if schedule (nullable) is None
        # and model_fields_set contains the field
        if self.schedule is None and "schedule" in self.model_fields_set:
            _dict['schedule'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IntermediaryTransactionUpdatedData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "preview": obj.get("preview") if obj.get("preview") is not None else False,
            "leg1_id": obj.get("leg1_id"),
            "leg2_id": obj.get("leg2_id"),
            "apikey": obj.get("apikey"),
            "leg1_sender_commission_id": obj.get("leg1_sender_commission_id"),
            "leg1_receiver_commission_id": obj.get("leg1_receiver_commission_id"),
            "leg2_sender_commission_id": obj.get("leg2_sender_commission_id"),
            "leg2_receiver_commission_id": obj.get("leg2_receiver_commission_id"),
            "workspace_id": obj.get("workspace_id"),
            "dt": obj.get("dt"),
            "comment": obj.get("comment"),
            "description": obj.get("description"),
            "project_id": obj.get("project_id"),
            "done": obj.get("done"),
            "forex": obj.get("forex"),
            "future_id": obj.get("future_id"),
            "future_edited": obj.get("future_edited"),
            "import_id": obj.get("import_id"),
            "import_hash": obj.get("import_hash"),
            "commission_applied": obj.get("commission_applied"),
            "schedule": IntermediaryTransactionCreatedDataSchedule.from_dict(obj["schedule"]) if obj.get("schedule") is not None else None,
            "labels": [IntermediaryTransactionCreatedDataLabelsInner.from_dict(_item) for _item in obj["labels"]] if obj.get("labels") is not None else None,
            "leg1": Transaction.from_dict(obj["leg1"]) if obj.get("leg1") is not None else None,
            "leg2": Transaction.from_dict(obj["leg2"]) if obj.get("leg2") is not None else None,
            "transactions": [EnrichedTransactionItem.from_dict(_item) for _item in obj["transactions"]] if obj.get("transactions") is not None else None,
            "removed_ids": obj.get("removed_ids"),
            "summary": AccountSummary.from_dict(obj["summary"]) if obj.get("summary") is not None else None
        })
        return _obj


