# coding: utf-8

"""
    Orbuculum API

    Orbuculum API documentation

    The version of the OpenAPI document: 0.39.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class MatchingKeywordPatternCreateRequest(BaseModel):
    """
    MatchingKeywordPatternCreateRequest
    """ # noqa: E501
    workspace_id: StrictInt
    trigger: Annotated[str, Field(strict=True, max_length=255)]
    trigger_type: Annotated[str, Field(strict=True, max_length=20)]
    sender_account_id: StrictInt
    receiver_account_id: StrictInt
    label_id: Optional[StrictInt] = None
    comment_template: Optional[StrictStr] = None
    confidence: Optional[Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]]] = None
    is_active: Optional[StrictBool] = True
    __properties: ClassVar[List[str]] = ["workspace_id", "trigger", "trigger_type", "sender_account_id", "receiver_account_id", "label_id", "comment_template", "confidence", "is_active"]

    @field_validator('trigger_type')
    def trigger_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['merchant_name', 'keyword', 'shortcut']):
            raise ValueError("must be one of enum values ('merchant_name', 'keyword', 'shortcut')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MatchingKeywordPatternCreateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if label_id (nullable) is None
        # and model_fields_set contains the field
        if self.label_id is None and "label_id" in self.model_fields_set:
            _dict['label_id'] = None

        # set to None if comment_template (nullable) is None
        # and model_fields_set contains the field
        if self.comment_template is None and "comment_template" in self.model_fields_set:
            _dict['comment_template'] = None

        # set to None if confidence (nullable) is None
        # and model_fields_set contains the field
        if self.confidence is None and "confidence" in self.model_fields_set:
            _dict['confidence'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MatchingKeywordPatternCreateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "workspace_id": obj.get("workspace_id"),
            "trigger": obj.get("trigger"),
            "trigger_type": obj.get("trigger_type"),
            "sender_account_id": obj.get("sender_account_id"),
            "receiver_account_id": obj.get("receiver_account_id"),
            "label_id": obj.get("label_id"),
            "comment_template": obj.get("comment_template"),
            "confidence": obj.get("confidence"),
            "is_active": obj.get("is_active") if obj.get("is_active") is not None else True
        })
        return _obj


