# coding: utf-8

"""
    Orbuculum API

    Orbuculum API documentation

    The version of the OpenAPI document: 0.39.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class MatchingAntiPatternCreateRequest(BaseModel):
    """
    MatchingAntiPatternCreateRequest
    """ # noqa: E501
    workspace_id: StrictInt
    input_summary: StrictStr
    rejected_sender_account_id: Optional[StrictInt] = None
    rejected_receiver_account_id: Optional[StrictInt] = None
    rejected_label_id: Optional[StrictInt] = None
    correct_sender_account_id: Optional[StrictInt] = None
    correct_receiver_account_id: Optional[StrictInt] = None
    correct_label_id: Optional[StrictInt] = None
    rejection_reason: Optional[StrictStr] = None
    source_example_id: Optional[StrictInt] = Field(default=None, description="FK to matching_examples")
    __properties: ClassVar[List[str]] = ["workspace_id", "input_summary", "rejected_sender_account_id", "rejected_receiver_account_id", "rejected_label_id", "correct_sender_account_id", "correct_receiver_account_id", "correct_label_id", "rejection_reason", "source_example_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MatchingAntiPatternCreateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if rejected_sender_account_id (nullable) is None
        # and model_fields_set contains the field
        if self.rejected_sender_account_id is None and "rejected_sender_account_id" in self.model_fields_set:
            _dict['rejected_sender_account_id'] = None

        # set to None if rejected_receiver_account_id (nullable) is None
        # and model_fields_set contains the field
        if self.rejected_receiver_account_id is None and "rejected_receiver_account_id" in self.model_fields_set:
            _dict['rejected_receiver_account_id'] = None

        # set to None if rejected_label_id (nullable) is None
        # and model_fields_set contains the field
        if self.rejected_label_id is None and "rejected_label_id" in self.model_fields_set:
            _dict['rejected_label_id'] = None

        # set to None if correct_sender_account_id (nullable) is None
        # and model_fields_set contains the field
        if self.correct_sender_account_id is None and "correct_sender_account_id" in self.model_fields_set:
            _dict['correct_sender_account_id'] = None

        # set to None if correct_receiver_account_id (nullable) is None
        # and model_fields_set contains the field
        if self.correct_receiver_account_id is None and "correct_receiver_account_id" in self.model_fields_set:
            _dict['correct_receiver_account_id'] = None

        # set to None if correct_label_id (nullable) is None
        # and model_fields_set contains the field
        if self.correct_label_id is None and "correct_label_id" in self.model_fields_set:
            _dict['correct_label_id'] = None

        # set to None if rejection_reason (nullable) is None
        # and model_fields_set contains the field
        if self.rejection_reason is None and "rejection_reason" in self.model_fields_set:
            _dict['rejection_reason'] = None

        # set to None if source_example_id (nullable) is None
        # and model_fields_set contains the field
        if self.source_example_id is None and "source_example_id" in self.model_fields_set:
            _dict['source_example_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MatchingAntiPatternCreateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "workspace_id": obj.get("workspace_id"),
            "input_summary": obj.get("input_summary"),
            "rejected_sender_account_id": obj.get("rejected_sender_account_id"),
            "rejected_receiver_account_id": obj.get("rejected_receiver_account_id"),
            "rejected_label_id": obj.get("rejected_label_id"),
            "correct_sender_account_id": obj.get("correct_sender_account_id"),
            "correct_receiver_account_id": obj.get("correct_receiver_account_id"),
            "correct_label_id": obj.get("correct_label_id"),
            "rejection_reason": obj.get("rejection_reason"),
            "source_example_id": obj.get("source_example_id")
        })
        return _obj


