# coding: utf-8

"""
    Orbuculum API

    Orbuculum API documentation

    The version of the OpenAPI document: 0.127.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from orbuculum_client.models.pnl_report_response_data_periods_inner_totals_gross_profit import PnlReportResponseDataPeriodsInnerTotalsGrossProfit
from orbuculum_client.models.pnl_report_response_data_periods_inner_totals_net_profit import PnlReportResponseDataPeriodsInnerTotalsNetProfit
from typing import Optional, Set
from typing_extensions import Self

class PnlReportResponseDataPeriodsInnerTotals(BaseModel):
    """
    Period totals, keyed. Replaces the legacy string-labelled summary rows. Every key is always present.
    """ # noqa: E501
    revenue: StrictInt = Field(description="Revenue rows summed, before direct revenue expenses. Positive.")
    revenue_kind: StrictStr = Field(description="Which caption the screen renders for `revenue`. The number is identical either way; only the label differs.")
    direct_revenue_expenses: StrictInt = Field(description="Negative: cost amounts arrive already signed and are added, never subtracted. 0 when the legacy row is absent.")
    net_revenue: StrictInt = Field(description="revenue + direct_revenue_expenses (the expense is already negative). Equals revenue when the legacy row is absent.")
    costs_of_revenue: StrictInt = Field(description="Negative; 0 when no cost-of-revenue accounts exist.")
    gross_profit: PnlReportResponseDataPeriodsInnerTotalsGrossProfit
    operating_expenses: StrictInt = Field(description="Negative-dominant. ALREADY INCLUDES this period's forex whenever the legacy folded it in; 0 when the legacy row is absent. Do not add forex to it.")
    net_profit: PnlReportResponseDataPeriodsInnerTotalsNetProfit
    __properties: ClassVar[List[str]] = ["revenue", "revenue_kind", "direct_revenue_expenses", "net_revenue", "costs_of_revenue", "gross_profit", "operating_expenses", "net_profit"]

    @field_validator('revenue_kind')
    def revenue_kind_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['gross_revenue', 'revenue']):
            raise ValueError("must be one of enum values ('gross_revenue', 'revenue')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PnlReportResponseDataPeriodsInnerTotals from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of gross_profit
        if self.gross_profit:
            _dict['gross_profit'] = self.gross_profit.to_dict()
        # override the default output from pydantic by calling `to_dict()` of net_profit
        if self.net_profit:
            _dict['net_profit'] = self.net_profit.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PnlReportResponseDataPeriodsInnerTotals from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "revenue": obj.get("revenue"),
            "revenue_kind": obj.get("revenue_kind"),
            "direct_revenue_expenses": obj.get("direct_revenue_expenses"),
            "net_revenue": obj.get("net_revenue"),
            "costs_of_revenue": obj.get("costs_of_revenue"),
            "gross_profit": PnlReportResponseDataPeriodsInnerTotalsGrossProfit.from_dict(obj["gross_profit"]) if obj.get("gross_profit") is not None else None,
            "operating_expenses": obj.get("operating_expenses"),
            "net_profit": PnlReportResponseDataPeriodsInnerTotalsNetProfit.from_dict(obj["net_profit"]) if obj.get("net_profit") is not None else None
        })
        return _obj


