# coding: utf-8

"""
    Orbuculum API

    Orbuculum API documentation

    The version of the OpenAPI document: 0.138.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List
from orbuculum_client.models.pnl_report_response_data_periods_inner_costs_inner import PnlReportResponseDataPeriodsInnerCostsInner
from orbuculum_client.models.pnl_report_response_data_periods_inner_period import PnlReportResponseDataPeriodsInnerPeriod
from orbuculum_client.models.pnl_report_response_data_periods_inner_revenue_inner import PnlReportResponseDataPeriodsInnerRevenueInner
from orbuculum_client.models.pnl_report_response_data_periods_inner_totals import PnlReportResponseDataPeriodsInnerTotals
from typing import Optional, Set
from typing_extensions import Self

class PnlReportResponseDataPeriodsInner(BaseModel):
    """
    PnlReportResponseDataPeriodsInner
    """ # noqa: E501
    period: PnlReportResponseDataPeriodsInnerPeriod
    revenue: List[PnlReportResponseDataPeriodsInnerRevenueInner] = Field(description="Revenue account rows. Positive: signs are emitted exactly as the backend computes them.")
    costs: List[PnlReportResponseDataPeriodsInnerCostsInner] = Field(description="Cost account rows. Amounts arrive negative; nothing is inverted.")
    forex: StrictInt = Field(description="FOREX gains/losses for the period; either sign. Rendered on its own line; already counted inside operating_expenses when the legacy folded it in.")
    totals: PnlReportResponseDataPeriodsInnerTotals
    __properties: ClassVar[List[str]] = ["period", "revenue", "costs", "forex", "totals"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PnlReportResponseDataPeriodsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of period
        if self.period:
            _dict['period'] = self.period.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in revenue (list)
        _items = []
        if self.revenue:
            for _item_revenue in self.revenue:
                if _item_revenue:
                    _items.append(_item_revenue.to_dict())
            _dict['revenue'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in costs (list)
        _items = []
        if self.costs:
            for _item_costs in self.costs:
                if _item_costs:
                    _items.append(_item_costs.to_dict())
            _dict['costs'] = _items
        # override the default output from pydantic by calling `to_dict()` of totals
        if self.totals:
            _dict['totals'] = self.totals.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PnlReportResponseDataPeriodsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "period": PnlReportResponseDataPeriodsInnerPeriod.from_dict(obj["period"]) if obj.get("period") is not None else None,
            "revenue": [PnlReportResponseDataPeriodsInnerRevenueInner.from_dict(_item) for _item in obj["revenue"]] if obj.get("revenue") is not None else None,
            "costs": [PnlReportResponseDataPeriodsInnerCostsInner.from_dict(_item) for _item in obj["costs"]] if obj.get("costs") is not None else None,
            "forex": obj.get("forex"),
            "totals": PnlReportResponseDataPeriodsInnerTotals.from_dict(obj["totals"]) if obj.get("totals") is not None else None
        })
        return _obj


