# coding: utf-8

"""
    Orbuculum API

    Orbuculum API documentation

    The version of the OpenAPI document: 0.124.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from orbuculum_client.models.project import Project
from typing import Optional, Set
from typing_extensions import Self

class TransactionCanonicalRow(BaseModel):
    """
    Canonical camelCase transaction wire shape (OMM-2102). Real booleans; amounts/balances/forex as strings to preserve precision.
    """ # noqa: E501
    id: StrictInt = Field(description="Transaction ID")
    dt: StrictStr = Field(description="Transaction date and time, emitted as explicit-offset ISO-8601 in the working timezone (X-Timezone header; UTC rendered with trailing Z when the header is absent or invalid), e.g. 2026-06-03T15:00:00+03:00. When `timeUnset` is true the value is instead the canonical naive 'YYYY-MM-DD 00:00:00' (no zone), stable across all X-Timezone values.")
    time_unset: StrictBool = Field(description="True when the transaction was saved with a date but no time. In that case `dt` is emitted as the canonical naive 'YYYY-MM-DD 00:00:00' and is stable across all X-Timezone values; the client should render date-only.", alias="timeUnset")
    comment: Optional[StrictStr] = Field(default=None, description="Transaction comment")
    done: StrictBool = Field(description="Transaction completion status (real JSON boolean)")
    apikey: Optional[StrictStr] = Field(default=None, description="External-integration identifier. NULL for transactions created directly via the UI.")
    forex: Optional[StrictStr] = Field(default=None, description="Per-transaction FX gain/loss amount in base-currency units, serialized as string to preserve precision. NULL until calculated.")
    sender_account_id: StrictInt = Field(description="Sender account ID", alias="senderAccountId")
    receiver_account_id: StrictInt = Field(description="Receiver account ID", alias="receiverAccountId")
    sender_amount: StrictStr = Field(description="Sender amount. Decimal value serialized as string to preserve precision; avoids JSON float rounding.", alias="senderAmount")
    receiver_amount: StrictStr = Field(description="Receiver amount. Decimal value serialized as string to preserve precision; avoids JSON float rounding.", alias="receiverAmount")
    sender_balance_after: Optional[StrictStr] = Field(default=None, description="Sender balance after transaction. Decimal value serialized as string to preserve precision; null when not computed.", alias="senderBalanceAfter")
    receiver_balance_after: Optional[StrictStr] = Field(default=None, description="Receiver balance after transaction. Decimal value serialized as string to preserve precision; null when not computed.", alias="receiverBalanceAfter")
    chained_id: Optional[StrictInt] = Field(default=None, description="ID of the paired transaction in a debt-pair. NULL for standalone transactions.", alias="chainedId")
    chained_commission_id: Optional[StrictInt] = Field(default=None, description="ID of the sender-side commission transaction generated alongside this transaction. NULL when no sender commission applies.", alias="chainedCommissionId")
    chained_receiver_commission: Optional[StrictInt] = Field(default=None, description="Integer FK (a transaction id) referencing the chained receiver commission transaction, despite the missing `_id` suffix. NULL when none.", alias="chainedReceiverCommission")
    import_id: Optional[StrictInt] = Field(default=None, description="ID of the import batch that created this transaction. NULL when not created via import.", alias="importId")
    is_initial: StrictBool = Field(description="True for initial-balance (IB) rows (dt earlier than 1971-01-01).", alias="isInitial")
    is_future: StrictBool = Field(description="True when the transaction is dated in the future relative to the seam (dt > NOW() + 59s, evaluated UTC; STRICT — dt == seam is false). Temporal flag only; recurrence is signalled separately by isRecurrent.", alias="isFuture")
    is_recurrent: StrictBool = Field(description="True when the transaction is part of a recurring schedule (future_id set). Drives the FE recurrence icon.", alias="isRecurrent")
    editable: Optional[StrictBool] = Field(default=None, description="Whether the requesting role may edit this transaction. May be null only in the context-less formatter path.")
    is_read_only: Optional[StrictBool] = Field(default=None, description="Inverse of editable. May be null only in the context-less formatter path.", alias="isReadOnly")
    project_id: Optional[StrictInt] = Field(default=None, description="Label FK — the API's legacy alias for the DB column `label_id` (API `project_id` == DB `label_id`). NULL when the transaction carries no label. NOTE: this is the transaction's LABEL id, NOT the workspace/tenant id.", alias="projectId")
    labels: Optional[List[Project]] = Field(default=None, description="Labels attached to this transaction. Currently at most one element, projected from `projectId`/`label_id`; always returned as an array for forward compatibility. Empty when the transaction has no label. Not permission-filtered: if the row is visible, its label is visible.")
    __properties: ClassVar[List[str]] = ["id", "dt", "timeUnset", "comment", "done", "apikey", "forex", "senderAccountId", "receiverAccountId", "senderAmount", "receiverAmount", "senderBalanceAfter", "receiverBalanceAfter", "chainedId", "chainedCommissionId", "chainedReceiverCommission", "importId", "isInitial", "isFuture", "isRecurrent", "editable", "isReadOnly", "projectId", "labels"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TransactionCanonicalRow from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in labels (list)
        _items = []
        if self.labels:
            for _item_labels in self.labels:
                if _item_labels:
                    _items.append(_item_labels.to_dict())
            _dict['labels'] = _items
        # set to None if comment (nullable) is None
        # and model_fields_set contains the field
        if self.comment is None and "comment" in self.model_fields_set:
            _dict['comment'] = None

        # set to None if apikey (nullable) is None
        # and model_fields_set contains the field
        if self.apikey is None and "apikey" in self.model_fields_set:
            _dict['apikey'] = None

        # set to None if forex (nullable) is None
        # and model_fields_set contains the field
        if self.forex is None and "forex" in self.model_fields_set:
            _dict['forex'] = None

        # set to None if sender_balance_after (nullable) is None
        # and model_fields_set contains the field
        if self.sender_balance_after is None and "sender_balance_after" in self.model_fields_set:
            _dict['senderBalanceAfter'] = None

        # set to None if receiver_balance_after (nullable) is None
        # and model_fields_set contains the field
        if self.receiver_balance_after is None and "receiver_balance_after" in self.model_fields_set:
            _dict['receiverBalanceAfter'] = None

        # set to None if chained_id (nullable) is None
        # and model_fields_set contains the field
        if self.chained_id is None and "chained_id" in self.model_fields_set:
            _dict['chainedId'] = None

        # set to None if chained_commission_id (nullable) is None
        # and model_fields_set contains the field
        if self.chained_commission_id is None and "chained_commission_id" in self.model_fields_set:
            _dict['chainedCommissionId'] = None

        # set to None if chained_receiver_commission (nullable) is None
        # and model_fields_set contains the field
        if self.chained_receiver_commission is None and "chained_receiver_commission" in self.model_fields_set:
            _dict['chainedReceiverCommission'] = None

        # set to None if import_id (nullable) is None
        # and model_fields_set contains the field
        if self.import_id is None and "import_id" in self.model_fields_set:
            _dict['importId'] = None

        # set to None if editable (nullable) is None
        # and model_fields_set contains the field
        if self.editable is None and "editable" in self.model_fields_set:
            _dict['editable'] = None

        # set to None if is_read_only (nullable) is None
        # and model_fields_set contains the field
        if self.is_read_only is None and "is_read_only" in self.model_fields_set:
            _dict['isReadOnly'] = None

        # set to None if project_id (nullable) is None
        # and model_fields_set contains the field
        if self.project_id is None and "project_id" in self.model_fields_set:
            _dict['projectId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TransactionCanonicalRow from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "dt": obj.get("dt"),
            "timeUnset": obj.get("timeUnset"),
            "comment": obj.get("comment"),
            "done": obj.get("done"),
            "apikey": obj.get("apikey"),
            "forex": obj.get("forex"),
            "senderAccountId": obj.get("senderAccountId"),
            "receiverAccountId": obj.get("receiverAccountId"),
            "senderAmount": obj.get("senderAmount"),
            "receiverAmount": obj.get("receiverAmount"),
            "senderBalanceAfter": obj.get("senderBalanceAfter"),
            "receiverBalanceAfter": obj.get("receiverBalanceAfter"),
            "chainedId": obj.get("chainedId"),
            "chainedCommissionId": obj.get("chainedCommissionId"),
            "chainedReceiverCommission": obj.get("chainedReceiverCommission"),
            "importId": obj.get("importId"),
            "isInitial": obj.get("isInitial"),
            "isFuture": obj.get("isFuture"),
            "isRecurrent": obj.get("isRecurrent"),
            "editable": obj.get("editable"),
            "isReadOnly": obj.get("isReadOnly"),
            "projectId": obj.get("projectId"),
            "labels": [Project.from_dict(_item) for _item in obj["labels"]] if obj.get("labels") is not None else None
        })
        return _obj


