# coding: utf-8

"""
    Orbuculum API

    Orbuculum API documentation

    The version of the OpenAPI document: 0.140.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class TransactionDraftRequest(BaseModel):
    """
    Filter inputs for the transaction-modal draft facade
    """ # noqa: E501
    workspace_id: StrictInt = Field(description="Workspace ID")
    subtab: Optional[StrictStr] = Field(default=None, description="Sub-tab to compose the draft for. Omit or send null to let the server derive it from the modal defaults.")
    label_id: Optional[StrictInt] = Field(default=None, description="Label (\"project\") override; must be manageable in this workspace")
    sender_id: Optional[StrictInt] = Field(default=None, description="Account already chosen in the sender slot")
    receiver_id: Optional[StrictInt] = Field(default=None, description="Account already chosen in the receiver slot")
    double_id: Optional[StrictInt] = Field(default=None, description="Account already chosen in the intermediary (double) slot")
    context_account_id: Optional[StrictInt] = Field(default=None, description="Account the modal was opened from; drives the derived tab/sub-tab and the suggestion")
    exclude_trx_id: Optional[StrictInt] = Field(default=None, description="A transaction that may not become its own anchor when the sub-tab is derived")
    dt: Optional[StrictStr] = Field(default=None, description="Date the modal is showing, 'Y-m-d H:i:s' in UTC. Selects the per-currency rate rows behind `form.rate`. Defaults to now.")
    __properties: ClassVar[List[str]] = ["workspace_id", "subtab", "label_id", "sender_id", "receiver_id", "double_id", "context_account_id", "exclude_trx_id", "dt"]

    @field_validator('subtab')
    def subtab_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['expenses', 'debt_to_costs', 'account_to_debt', 'double_expenses', 'income', 'revenue_to_debt', 'debt_to_account', 'double_income', 'transfer', 'debt_to_debt', 'double_transfer', 'custom']):
            raise ValueError("must be one of enum values ('expenses', 'debt_to_costs', 'account_to_debt', 'double_expenses', 'income', 'revenue_to_debt', 'debt_to_account', 'double_income', 'transfer', 'debt_to_debt', 'double_transfer', 'custom')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TransactionDraftRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if subtab (nullable) is None
        # and model_fields_set contains the field
        if self.subtab is None and "subtab" in self.model_fields_set:
            _dict['subtab'] = None

        # set to None if label_id (nullable) is None
        # and model_fields_set contains the field
        if self.label_id is None and "label_id" in self.model_fields_set:
            _dict['label_id'] = None

        # set to None if sender_id (nullable) is None
        # and model_fields_set contains the field
        if self.sender_id is None and "sender_id" in self.model_fields_set:
            _dict['sender_id'] = None

        # set to None if receiver_id (nullable) is None
        # and model_fields_set contains the field
        if self.receiver_id is None and "receiver_id" in self.model_fields_set:
            _dict['receiver_id'] = None

        # set to None if double_id (nullable) is None
        # and model_fields_set contains the field
        if self.double_id is None and "double_id" in self.model_fields_set:
            _dict['double_id'] = None

        # set to None if context_account_id (nullable) is None
        # and model_fields_set contains the field
        if self.context_account_id is None and "context_account_id" in self.model_fields_set:
            _dict['context_account_id'] = None

        # set to None if exclude_trx_id (nullable) is None
        # and model_fields_set contains the field
        if self.exclude_trx_id is None and "exclude_trx_id" in self.model_fields_set:
            _dict['exclude_trx_id'] = None

        # set to None if dt (nullable) is None
        # and model_fields_set contains the field
        if self.dt is None and "dt" in self.model_fields_set:
            _dict['dt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TransactionDraftRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "workspace_id": obj.get("workspace_id"),
            "subtab": obj.get("subtab"),
            "label_id": obj.get("label_id"),
            "sender_id": obj.get("sender_id"),
            "receiver_id": obj.get("receiver_id"),
            "double_id": obj.get("double_id"),
            "context_account_id": obj.get("context_account_id"),
            "exclude_trx_id": obj.get("exclude_trx_id"),
            "dt": obj.get("dt")
        })
        return _obj


