# coding: utf-8

"""
    Orbuculum API

    Orbuculum API documentation

    The version of the OpenAPI document: 0.49.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from orbuculum_client.models.update_transaction_response_data_commissions import UpdateTransactionResponseDataCommissions
from typing import Optional, Set
from typing_extensions import Self

class UpdateTransactionResponseData(BaseModel):
    """
    UpdateTransactionResponseData
    """ # noqa: E501
    id: Optional[StrictInt] = None
    old_attributes: Optional[Dict[str, Any]] = Field(default=None, description="Pre-update field snapshot (free-form)")
    commissions: Optional[UpdateTransactionResponseDataCommissions] = None
    transactions: Optional[List[Dict[str, Any]]] = Field(default=None, description="Enriched transactions list (present only when request includes account_id)")
    removed_ids: Optional[List[StrictInt]] = Field(default=None, description="IDs removed from the account view (present only when request includes account_id)")
    summary: Optional[Dict[str, Any]] = Field(default=None, description="Account summary recompute (present only when request includes account_id)")
    __properties: ClassVar[List[str]] = ["id", "old_attributes", "commissions", "transactions", "removed_ids", "summary"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateTransactionResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of commissions
        if self.commissions:
            _dict['commissions'] = self.commissions.to_dict()
        # set to None if transactions (nullable) is None
        # and model_fields_set contains the field
        if self.transactions is None and "transactions" in self.model_fields_set:
            _dict['transactions'] = None

        # set to None if removed_ids (nullable) is None
        # and model_fields_set contains the field
        if self.removed_ids is None and "removed_ids" in self.model_fields_set:
            _dict['removed_ids'] = None

        # set to None if summary (nullable) is None
        # and model_fields_set contains the field
        if self.summary is None and "summary" in self.model_fields_set:
            _dict['summary'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateTransactionResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "old_attributes": obj.get("old_attributes"),
            "commissions": UpdateTransactionResponseDataCommissions.from_dict(obj["commissions"]) if obj.get("commissions") is not None else None,
            "transactions": obj.get("transactions"),
            "removed_ids": obj.get("removed_ids"),
            "summary": obj.get("summary")
        })
        return _obj


