# coding: utf-8

"""
    Orbuculum API

    Orbuculum API documentation

    The version of the OpenAPI document: 0.49.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class UpdateScheduledTransactionRequest(BaseModel):
    """
    UpdateScheduledTransactionRequest
    """ # noqa: E501
    workspace_id: StrictInt = Field(description="Workspace ID")
    id: StrictInt = Field(description="Scheduled transaction ID")
    edit_type: StrictInt = Field(description="Edit type: 1=ALL, 2=SINGLE, 3=THIS_AND_FUTURE")
    trx_id: Optional[StrictInt] = Field(default=None, description="Transaction ID (required for edit_type=2)")
    trx_id_2: Optional[StrictInt] = Field(default=None, description="Second transaction ID for intermediary (edit_type=2)")
    override: Optional[StrictBool] = Field(default=None, description="Override edited transactions")
    sender_account_id: Optional[StrictInt] = Field(default=None, description="Sender account ID")
    receiver_account_id: Optional[StrictInt] = Field(default=None, description="Receiver account ID")
    sender_amount: Optional[StrictStr] = Field(default=None, description="Sender amount")
    receiver_amount: Optional[StrictStr] = Field(default=None, description="Receiver amount")
    dt: Optional[date] = Field(default=None, description="Date")
    time: Optional[StrictStr] = Field(default=None, description="Time")
    timezone: Optional[StrictStr] = Field(default=None, description="Timezone")
    schedule_type: Optional[StrictInt] = Field(default=None, description="Schedule type (1-8)")
    comment: Optional[StrictStr] = Field(default=None, description="Comment")
    description: Optional[StrictStr] = Field(default=None, description="Description")
    __properties: ClassVar[List[str]] = ["workspace_id", "id", "edit_type", "trx_id", "trx_id_2", "override", "sender_account_id", "receiver_account_id", "sender_amount", "receiver_amount", "dt", "time", "timezone", "schedule_type", "comment", "description"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateScheduledTransactionRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if trx_id (nullable) is None
        # and model_fields_set contains the field
        if self.trx_id is None and "trx_id" in self.model_fields_set:
            _dict['trx_id'] = None

        # set to None if trx_id_2 (nullable) is None
        # and model_fields_set contains the field
        if self.trx_id_2 is None and "trx_id_2" in self.model_fields_set:
            _dict['trx_id_2'] = None

        # set to None if comment (nullable) is None
        # and model_fields_set contains the field
        if self.comment is None and "comment" in self.model_fields_set:
            _dict['comment'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateScheduledTransactionRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "workspace_id": obj.get("workspace_id"),
            "id": obj.get("id"),
            "edit_type": obj.get("edit_type"),
            "trx_id": obj.get("trx_id"),
            "trx_id_2": obj.get("trx_id_2"),
            "override": obj.get("override"),
            "sender_account_id": obj.get("sender_account_id"),
            "receiver_account_id": obj.get("receiver_account_id"),
            "sender_amount": obj.get("sender_amount"),
            "receiver_amount": obj.get("receiver_amount"),
            "dt": obj.get("dt"),
            "time": obj.get("time"),
            "timezone": obj.get("timezone"),
            "schedule_type": obj.get("schedule_type"),
            "comment": obj.get("comment"),
            "description": obj.get("description")
        })
        return _obj


